site_name: m5-201 
site_url: https://paulcccccch.github.io/
site_author: DATA Course Team Led by Chonghan Chen
site_description: IceWould Training Hub

theme:
  name: cinder

nav:
  - Home: index.md
  - Current Schedule: schedule.md
  - Spring 2021 Version: schedule-21-spring.md

repo_url: https://github.com/PaulCCCCCCH/m5-201
site_dir: m5-201/
